name: CI Pipeline

on: push

jobs:
  run-dvc-pipeline:
    runs-on: ubuntu-latest

    steps:

      - name: code checkout
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: configure DagsHub credentials
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          echo "machine dagshub.com" > ~/.netrc
          echo "login $DAGSHUB_PAT" >> ~/.netrc
          echo "password $DAGSHUB_PAT" >> ~/.netrc

      - name: run pipeline
        run: |
          dvc repro